// ─── Plunk Email Service ───
// Uses the Plunk REST API (https://docs.useplunk.com) to send transactional emails.

const PLUNK_API_URL = "https://api.useplunk.com/v1";

interface SendEmailOptions {
  to: string;
  subject: string;
  body: string; // HTML body
}

interface PlunkResponse {
  success: boolean;
  emails?: { contact: { id: string } }[];
  error?: string;
  statusCode?: number;
}

export async function sendEmail(opts: SendEmailOptions): Promise<PlunkResponse> {
  const apiKey = process.env.PLUNK_API_KEY;
  if (!apiKey) throw new Error("PLUNK_API_KEY is not set");

  const res = await fetch(`${PLUNK_API_URL}/send`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      to: opts.to,
      subject: opts.subject,
      body: opts.body,
    }),
  });

  const data = await res.json();

  if (!res.ok) {
    return {
      success: false,
      error: data?.message ?? "Unknown Plunk error",
      statusCode: res.status,
    };
  }

  return { success: true, emails: data?.emails };
}

// ─── Flood alert email template ───
export function buildFloodAlertEmail(params: {
  userName: string;
  locationLabel: string;
  city: string;
  riskLevel: string;
  reasoning: string;
  suggestedAction: string;
  leadTimeHours: number | null;
}): { subject: string; body: string } {
  const riskColors: Record<string, string> = {
    low: "#3b82f6",
    moderate: "#f59e0b",
    high: "#f97316",
    extreme: "#ef4444",
  };

  const color = riskColors[params.riskLevel] ?? "#6b7280";
  const leadText = params.leadTimeHours
    ? `Expected in approximately <strong>${params.leadTimeHours} hours</strong>.`
    : "";

  const subject = `⚠️ FloodNet Alert: ${params.riskLevel.toUpperCase()} flood risk in ${params.city}`;

  const body = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #0c4a6e 0%, #0369a1 100%); padding: 24px; border-radius: 12px 12px 0 0;">
        <h1 style="color: white; margin: 0; font-size: 24px;">🌊 FloodNet Alert</h1>
        <p style="color: rgba(255,255,255,0.85); margin: 8px 0 0;">Weather Safety Notification</p>
      </div>

      <div style="border: 1px solid #e5e7eb; border-top: none; padding: 24px; border-radius: 0 0 12px 12px;">
        <p style="margin: 0 0 16px;">Hi ${params.userName},</p>

        <div style="background: ${color}15; border-left: 4px solid ${color}; padding: 16px; border-radius: 0 8px 8px 0; margin-bottom: 20px;">
          <p style="margin: 0; font-weight: 600; color: ${color}; font-size: 18px;">
            ${params.riskLevel.toUpperCase()} Risk — ${params.locationLabel}
          </p>
          <p style="margin: 8px 0 0; color: #374151;">${params.city}</p>
        </div>

        <h3 style="margin: 0 0 8px; color: #111827;">Assessment</h3>
        <p style="color: #4b5563; line-height: 1.6; margin: 0 0 16px;">${params.reasoning}</p>

        ${leadText ? `<p style="color: #4b5563; margin: 0 0 16px;">${leadText}</p>` : ""}

        <h3 style="margin: 0 0 8px; color: #111827;">Recommended Action</h3>
        <p style="color: #4b5563; line-height: 1.6; margin: 0 0 24px;">${params.suggestedAction}</p>

        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;" />
        <p style="color: #9ca3af; font-size: 12px; margin: 0;">
          This alert was generated by FloodNet AI. You can manage your alert preferences in your dashboard.
        </p>
      </div>
    </div>
  `;

  return { subject, body };
}
